// ===================== PELANGGAN & BILLING =====================
// Dipakai oleh: Admin, CS (lihat data pelanggan + input pembayaran)

var _pelangganData = [];
var _pelangganFilter = 'SEMUA';
var _pelangganTipe   = 'SEMUA';

// ── Helpers ──────────────────────────────────────────────────
function plgText(v) {
  return String(v == null ? '' : v).replace(/[&<>"']/g, c =>
    ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
}
function plgFmt(v) {
  return Number(v||0).toLocaleString('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0});
}
function plgDate(s) {
  if(!s) return '-';
  const d = new Date(String(s)+'T00:00:00');
  return d.toLocaleDateString('id-ID',{day:'2-digit',month:'short',year:'numeric'});
}
function plgAddDays(dateStr, days) {
  const d = new Date(String(dateStr)+'T00:00:00');
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0,10);
}
function plgToday() {
  return new Date().toISOString().slice(0,10);
}
function plgDaysDiff(dateStr) {
  if(!dateStr) return null;
  const diff = new Date(String(dateStr)+'T00:00:00') - new Date(plgToday()+'T00:00:00');
  return Math.ceil(diff / 86400000);
}

function plgStatusBadge(status, tanggalJatuhTempo) {
  const sisa = plgDaysDiff(tanggalJatuhTempo);
  if(status === 'AKTIF') {
    if(sisa !== null && sisa <= 7 && sisa >= 0) {
      return `<span class="px-2.5 py-1 rounded-lg text-[10px] font-extrabold bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300"><i class="fa-solid fa-triangle-exclamation mr-1"></i>Aktif (Jatuh Tempo ${sisa}h)</span>`;
    }
    return `<span class="px-2.5 py-1 rounded-lg text-[10px] font-extrabold bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-300"><i class="fa-solid fa-circle-check mr-1"></i>Aktif</span>`;
  }
  if(status === 'SUSPEND') {
    return `<span class="px-2.5 py-1 rounded-lg text-[10px] font-extrabold bg-rose-100 text-rose-700 dark:bg-rose-900/40 dark:text-rose-300 animate-pulse"><i class="fa-solid fa-ban mr-1"></i>Suspend</span>`;
  }
  if(status === 'DISMANTLE') {
    return `<span class="px-2.5 py-1 rounded-lg text-[10px] font-extrabold bg-slate-200 text-slate-600 dark:bg-slate-700 dark:text-slate-400"><i class="fa-solid fa-plug-circle-xmark mr-1"></i>Dismantle</span>`;
  }
  if(status === 'NONAKTIF') {
    return `<span class="px-2.5 py-1 rounded-lg text-[10px] font-extrabold bg-slate-100 text-slate-500"><i class="fa-solid fa-circle-minus mr-1"></i>Nonaktif</span>`;
  }
  return `<span class="px-2.5 py-1 rounded-lg text-[10px] font-extrabold bg-slate-100 text-slate-500">${plgText(status)}</span>`;
}

function plgTipeBadge(tipe) {
  const map = {
    INSTALASI:          'bg-blue-100 text-blue-700',
    INSTALASI_RESELLER: 'bg-cyan-100 text-cyan-700',
    PERLUASAN_RESELLER: 'bg-teal-100 text-teal-700'
  };
  const label = {
    INSTALASI:          'Instalasi Baru',
    INSTALASI_RESELLER: 'Instalasi Reseller',
    PERLUASAN_RESELLER: 'Perluasan'
  };
  return `<span class="px-2 py-0.5 rounded-full text-[9px] font-extrabold ${map[tipe]||'bg-slate-100 text-slate-600'}">${label[tipe]||tipe}</span>`;
}

// ── AUTO BILLING CHECK ────────────────────────────────────────
// Cek semua pelanggan AKTIF/SUSPEND dan update status otomatis
async function runBillingCheck() {
  const today = plgToday();
  try {
    // 1. AKTIF → SUSPEND (jatuh tempo terlewat)
    const { data: toSuspend, error: e1 } = await supa.from('pelanggan')
      .select('id, nama, no_layanan, tanggal_jatuh_tempo')
      .eq('status_billing','AKTIF')
      .lte('tanggal_jatuh_tempo', today);
    if(e1) throw e1;
    for(const p of (toSuspend||[])) {
      await supa.from('pelanggan').update({
        status_billing: 'SUSPEND',
        tanggal_suspend: today,
        updated_at: new Date().toISOString()
      }).eq('id', p.id);
      console.log(`[Billing] ${p.nama} → SUSPEND`);
    }

    // 2. SUSPEND → DISMANTLE (sudah 14 hari sejak suspend)
    const suspendLimit = plgAddDays(today, -14);
    const { data: toDismantle, error: e2 } = await supa.from('pelanggan')
      .select('id, nama, no_layanan, alamat, koordinat, wo_id, teknisi_nama, sumber, mitra_id, mitra_nama')
      .eq('status_billing','SUSPEND')
      .lte('tanggal_suspend', suspendLimit);
    if(e2) throw e2;
    for(const p of (toDismantle||[])) {
      await autoGenerateDismantle(p, today);
    }
  } catch(err) {
    console.warn('[Billing] Auto-check error:', err.message);
  }
}

async function autoGenerateDismantle(pelanggan, today) {
  try {
    // Cek apakah sudah ada dismantle WO untuk pelanggan ini
    const { data: existing } = await supa.from('work_orders')
      .select('wo_id').eq('pelanggan_id', pelanggan.id).eq('is_auto_dismantle', true).maybeSingle();
    if(existing) return; // sudah ada, skip

    // Generate WO dismantle otomatis
    const now = new Date();
    const woId = 'WO-AUTO-' + now.getFullYear().toString().slice(-2)
      + String(now.getMonth()+1).padStart(2,'0')
      + String(now.getDate()).padStart(2,'0')
      + '-' + String(Math.floor(Math.random()*900)+100);

    const { error: woErr } = await supa.from('work_orders').insert({
      wo_id:            woId,
      pelanggan:        pelanggan.nama,
      tipe:             'DISMANTLE',
      cs_name:          'Sistem (Auto Billing)',
      teknisi:          [],
      teknisi_1:        null,
      t1:               now.toTimeString().slice(0,5),
      t2:               now.toTimeString().slice(0,5),
      status:           'RELEASE',
      bulan:            now.getMonth(),
      tahun:            now.getFullYear(),
      tanggal:          today,
      alamat:           pelanggan.alamat || '',
      koordinat:        pelanggan.koordinat || null,
      kendala:          `Auto-dismantle: pelanggan ${pelanggan.nama} (${pelanggan.no_layanan||'-'}) belum bayar 14 hari setelah suspend.`,
      mitra_id:         pelanggan.mitra_id || null,
      is_auto_dismantle: true,
      pelanggan_id:     pelanggan.id,
      released_at:      now.toISOString()
    });
    if(woErr) throw woErr;

    // Update status pelanggan → DISMANTLE
    await supa.from('pelanggan').update({
      status_billing:  'DISMANTLE',
      dismantle_wo_id: woId,
      dismantle_at:    now.toISOString(),
      updated_at:      now.toISOString()
    }).eq('id', pelanggan.id);

    console.log(`[Billing] ${pelanggan.nama} → DISMANTLE, WO: ${woId}`);
  } catch(err) {
    console.warn(`[Billing] Gagal auto-dismantle ${pelanggan.nama}:`, err.message);
  }
}

// ── CREATE PELANGGAN (dipanggil saat WO DONE) ─────────────────
async function createPelangganFromWO(wo) {
  // Cek sudah ada atau belum
  const { data: exists } = await supa.from('pelanggan')
    .select('id').eq('wo_id', wo.wo_id).maybeSingle();
  if(exists) return;

  if(!['INSTALASI','INSTALASI_RESELLER','PERLUASAN_RESELLER'].includes(wo.tipe)) return;

  const today = plgToday();
  const jatuhTempo = plgAddDays(today, 30);

  // Tentukan sumber: cek mitra_id di work_orders
  const sumber = wo.mitra_id ? 'mitra' : 'internal';

  // Ambil nama mitra jika ada
  let mitraNama = null;
  if(wo.mitra_id) {
    const { data: mitra } = await supa.from('mitra').select('nama').eq('id', wo.mitra_id).maybeSingle();
    mitraNama = mitra ? mitra.nama : null;
  }

  await supa.from('pelanggan').insert({
    wo_id:               wo.wo_id,
    no_layanan:          wo.no_layanan || null,
    nama:                wo.pelanggan,
    no_hp:               wo.no_hp || null,
    alamat:              wo.alamat || null,
    koordinat:           wo.koordinat || null,
    paket:               wo.nama_paket || null,
    harga_paket:         wo.paket || 0,
    tipe_instalasi:      wo.tipe,
    tanggal_aktif:       today,
    tanggal_jatuh_tempo: jatuhTempo,
    status_billing:      'AKTIF',
    sumber,
    mitra_id:            wo.mitra_id || null,
    mitra_nama:          mitraNama,
    teknisi_nama:        wo.teknisi_1 || null
  });
}

// ── LOAD DATA PELANGGAN ───────────────────────────────────────
async function loadDataPelanggan() {
  const el = document.getElementById('pelanggan-list');
  if(!el) return;

  // Jalankan billing check dulu
  await runBillingCheck();

  el.innerHTML = '<div class="text-xs text-slate-400 text-center py-6"><i class="fa-solid fa-spinner animate-spin mr-1"></i>Memuat data pelanggan...</div>';

  const statusFilter = (document.getElementById('plg-filter-status')||{value:'SEMUA'}).value || 'SEMUA';
  const tipeFilter   = (document.getElementById('plg-filter-tipe')||{value:'SEMUA'}).value   || 'SEMUA';
  const sumberFilter = (document.getElementById('plg-filter-sumber')||{value:'SEMUA'}).value || 'SEMUA';
  const cariVal      = ((document.getElementById('plg-cari')||{value:''}).value||'').toLowerCase().trim();

  try {
    let query = supa.from('pelanggan')
      .select('*')
      .order('created_at', {ascending: false})
      .limit(500);

    if(statusFilter !== 'SEMUA') query = query.eq('status_billing', statusFilter);
    if(tipeFilter   !== 'SEMUA') query = query.eq('tipe_instalasi', tipeFilter);
    if(sumberFilter !== 'SEMUA') query = query.eq('sumber', sumberFilter);

    const { data, error } = await query;
    if(error) throw error;

    let rows = data || [];
    if(cariVal) {
      rows = rows.filter(p =>
        (p.nama||'').toLowerCase().includes(cariVal) ||
        (p.no_layanan||'').toLowerCase().includes(cariVal) ||
        (p.no_hp||'').toLowerCase().includes(cariVal) ||
        (p.alamat||'').toLowerCase().includes(cariVal)
      );
    }
    _pelangganData = rows;

    if(!rows.length) {
      el.innerHTML = '<div class="text-xs text-slate-400 text-center py-8"><i class="fa-solid fa-inbox text-2xl block mb-2"></i>Tidak ada data pelanggan.</div>';
      updatePelangganSummary([]);
      return;
    }

    updatePelangganSummary(rows);
    renderPelangganTable(rows);
  } catch(err) {
    el.innerHTML = `<div class="text-xs text-rose-500 text-center py-4">Gagal memuat: ${plgText(err.message)}</div>`;
  }
}

function updatePelangganSummary(rows) {
  const aktif    = rows.filter(p => p.status_billing === 'AKTIF').length;
  const suspend  = rows.filter(p => p.status_billing === 'SUSPEND').length;
  const dismantle= rows.filter(p => p.status_billing === 'DISMANTLE').length;
  const total    = rows.length;

  const set = (id, val) => { const el = document.getElementById(id); if(el) el.textContent = val; };
  set('plg-summary-total',    total);
  set('plg-summary-aktif',    aktif);
  set('plg-summary-suspend',  suspend);
  set('plg-summary-dismantle',dismantle);
}

function renderPelangganTable(rows) {
  const el = document.getElementById('pelanggan-list');
  if(!el) return;
  const isAdmin = currentUser && ['admin','owner','supervisor','spv'].includes(String(currentUser.role||'').toLowerCase());

  el.innerHTML = `
    <div class="overflow-x-auto">
      <table class="w-full text-xs min-w-[700px]">
        <thead class="bg-slate-50 dark:bg-slate-700/50">
          <tr>
            <th class="py-2.5 px-3 text-left font-extrabold text-slate-500 uppercase">Pelanggan</th>
            <th class="py-2.5 px-3 text-left font-extrabold text-slate-500 uppercase">No. Layanan</th>
            <th class="py-2.5 px-3 text-left font-extrabold text-slate-500 uppercase">Tipe</th>
            <th class="py-2.5 px-3 text-center font-extrabold text-slate-500 uppercase">Status</th>
            <th class="py-2.5 px-3 text-left font-extrabold text-slate-500 uppercase">Jatuh Tempo</th>
            <th class="py-2.5 px-3 text-left font-extrabold text-slate-500 uppercase">Sumber</th>
            ${isAdmin ? '<th class="py-2.5 px-3 text-center font-extrabold text-slate-500 uppercase">Aksi</th>' : ''}
          </tr>
        </thead>
        <tbody class="divide-y divide-slate-100 dark:divide-slate-700">
          ${rows.map(p => {
            const sisa = plgDaysDiff(p.tanggal_jatuh_tempo);
            const sisaText = sisa === null ? '-'
              : sisa > 0 ? `${sisa} hari lagi`
              : sisa === 0 ? '<span class="text-amber-600 font-bold">Hari ini</span>'
              : `<span class="text-rose-500 font-bold">${Math.abs(sisa)} hari lewat</span>`;
            const sumberBadge = p.sumber === 'mitra'
              ? `<span class="px-2 py-0.5 rounded-full text-[9px] font-black bg-orange-100 text-orange-700"><i class="fa-solid fa-handshake mr-0.5"></i>${plgText(p.mitra_nama||'Mitra')}</span>`
              : `<span class="px-2 py-0.5 rounded-full text-[9px] font-black bg-slate-100 text-slate-600"><i class="fa-solid fa-building mr-0.5"></i>Internal</span>`;
            const aksiBtn = isAdmin ? `<td class="py-2.5 px-3 text-center">
              <button onclick="bukaPelangganDetail('${p.id}')" class="px-2.5 py-1 bg-indigo-100 hover:bg-indigo-200 text-indigo-700 rounded-lg text-[10px] font-bold">
                <i class="fa-solid fa-eye"></i>
              </button>
            </td>` : '';
            return `<tr class="hover:bg-slate-50/80 dark:hover:bg-slate-700/40 transition-all">
              <td class="py-2.5 px-3">
                <p class="font-bold text-slate-800 dark:text-slate-100">${plgText(p.nama)}</p>
                <p class="text-[10px] text-slate-400">${plgText(p.no_hp||'-')}</p>
              </td>
              <td class="py-2.5 px-3 font-mono font-bold text-slate-700 dark:text-slate-200">${plgText(p.no_layanan||'-')}</td>
              <td class="py-2.5 px-3">${plgTipeBadge(p.tipe_instalasi)}</td>
              <td class="py-2.5 px-3 text-center">${plgStatusBadge(p.status_billing, p.tanggal_jatuh_tempo)}</td>
              <td class="py-2.5 px-3">
                <p class="font-semibold text-slate-700 dark:text-slate-200">${plgDate(p.tanggal_jatuh_tempo)}</p>
                <p class="text-[10px] text-slate-400">${sisaText}</p>
              </td>
              <td class="py-2.5 px-3">${sumberBadge}</td>
              ${aksiBtn}
            </tr>`;
          }).join('')}
        </tbody>
      </table>
    </div>`;
}

// ── DETAIL PELANGGAN ─────────────────────────────────────────
async function bukaPelangganDetail(id) {
  const modal = document.getElementById('pelanggan-detail-modal');
  const body  = document.getElementById('pelanggan-detail-body');
  if(!modal || !body) return;

  body.innerHTML = '<p class="text-center py-6 text-slate-400 text-xs"><i class="fa-solid fa-spinner animate-spin mr-1"></i>Memuat...</p>';
  modal.classList.remove('hidden');

  try {
    const { data: p, error } = await supa.from('pelanggan').select('*').eq('id', id).single();
    if(error) throw error;

    // Ambil riwayat pembayaran
    const { data: payments } = await supa.from('pembayaran')
      .select('*').eq('pelanggan_id', id).order('created_at',{ascending:false}).limit(10);

    const sisa = plgDaysDiff(p.tanggal_jatuh_tempo);
    body.innerHTML = `
      <div class="space-y-4">
        <div class="grid grid-cols-2 gap-3 text-xs">
          <div class="col-span-2 bg-slate-50 dark:bg-slate-700/40 rounded-xl p-3 space-y-1">
            <p class="text-[10px] font-bold text-slate-400 uppercase">Info Pelanggan</p>
            <p class="font-extrabold text-slate-900 dark:text-white text-sm">${plgText(p.nama)}</p>
            <p class="text-slate-500">${plgText(p.no_hp||'-')} • ${plgText(p.alamat||'-')}</p>
            <div class="flex items-center gap-2 flex-wrap mt-1">
              ${plgTipeBadge(p.tipe_instalasi)}
              ${plgStatusBadge(p.status_billing, p.tanggal_jatuh_tempo)}
            </div>
          </div>
          <div class="bg-slate-50 dark:bg-slate-700/40 rounded-xl p-3 space-y-1">
            <p class="text-[10px] font-bold text-slate-400 uppercase">Billing</p>
            <p><span class="text-slate-400">No. Layanan:</span> <span class="font-bold font-mono">${plgText(p.no_layanan||'-')}</span></p>
            <p><span class="text-slate-400">Mulai:</span> <span class="font-semibold">${plgDate(p.tanggal_aktif)}</span></p>
            <p><span class="text-slate-400">Bayar Terakhir:</span> <span class="font-semibold">${plgDate(p.tanggal_bayar_terakhir)}</span></p>
            <p><span class="text-slate-400">Jatuh Tempo:</span> <span class="font-semibold ${sisa !== null && sisa < 0 ? 'text-rose-500' : ''}">${plgDate(p.tanggal_jatuh_tempo)}</span></p>
          </div>
          <div class="bg-slate-50 dark:bg-slate-700/40 rounded-xl p-3 space-y-1">
            <p class="text-[10px] font-bold text-slate-400 uppercase">Paket</p>
            <p class="font-semibold">${plgText(p.paket||'-')}</p>
            <p class="font-bold text-emerald-600">${plgFmt(p.harga_paket)}/bln</p>
            <p><span class="text-slate-400">Teknisi:</span> <span class="font-semibold">${plgText(p.teknisi_nama||'-')}</span></p>
            <p><span class="text-slate-400">Sumber:</span> <span class="font-semibold">${p.sumber === 'mitra' ? plgText(p.mitra_nama) : 'Internal'}</span></p>
          </div>
        </div>
        <div>
          <p class="text-[10px] font-bold text-slate-400 uppercase mb-2">Riwayat Pembayaran</p>
          ${(payments||[]).length === 0
            ? '<p class="text-xs text-slate-400 text-center py-3">Belum ada pembayaran.</p>'
            : (payments||[]).map(pay => {
                const statusMap = {MENUNGGU:'bg-amber-100 text-amber-700', DIKONFIRMASI:'bg-emerald-100 text-emerald-700', DITOLAK:'bg-rose-100 text-rose-700'};
                return `<div class="flex items-center justify-between gap-2 py-2 border-b border-slate-100 dark:border-slate-700 last:border-0">
                  <div>
                    <p class="font-semibold text-slate-800 dark:text-slate-100">${plgDate(pay.tanggal_bayar)} • ${plgFmt(pay.jumlah)}</p>
                    <p class="text-[10px] text-slate-400">Input: ${plgText(pay.input_oleh)} ${pay.konfirmasi_oleh ? '• Konfirmasi: '+plgText(pay.konfirmasi_oleh) : ''}</p>
                  </div>
                  <span class="px-2 py-0.5 rounded-full text-[9px] font-black ${statusMap[pay.status]||'bg-slate-100 text-slate-600'}">${plgText(pay.status)}</span>
                </div>`;
              }).join('')}
        </div>
        ${p.status_billing === 'SUSPEND' ? `
        <button onclick="tutupPelangganDetail();bukaFormPembayaran('${p.id}','${plgText(p.nama)}','${plgText(p.no_layanan||'')}')"
          class="w-full py-2.5 bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs rounded-xl flex items-center justify-center gap-2">
          <i class="fa-solid fa-money-bill-wave"></i>Input Pembayaran
        </button>` : ''}
      </div>`;
  } catch(err) {
    body.innerHTML = `<p class="text-xs text-rose-500 text-center py-4">Gagal: ${plgText(err.message)}</p>`;
  }
}

function tutupPelangganDetail() {
  const modal = document.getElementById('pelanggan-detail-modal');
  if(modal) modal.classList.add('hidden');
}

// ── FORM PEMBAYARAN (CS Input) ────────────────────────────────
function bukaFormPembayaran(pelangganId, namaPelanggan, noLayanan) {
  const modal = document.getElementById('pembayaran-form-modal');
  if(!modal) return;
  document.getElementById('pay-pelanggan-id').value   = pelangganId  || '';
  document.getElementById('pay-nama-display').textContent = namaPelanggan || '';
  document.getElementById('pay-no-layanan-display').textContent = noLayanan || '-';
  document.getElementById('pay-tanggal').value         = plgToday();
  document.getElementById('pay-jumlah').value          = '';
  document.getElementById('pay-catatan').value         = '';
  document.getElementById('pay-bukti').value           = '';
  modal.classList.remove('hidden');
}

function tutupFormPembayaran() {
  const modal = document.getElementById('pembayaran-form-modal');
  if(modal) modal.classList.add('hidden');
}

async function submitPembayaran(e) {
  e.preventDefault();
  const pelangganId = document.getElementById('pay-pelanggan-id').value;
  const tanggal     = document.getElementById('pay-tanggal').value;
  const jumlah      = parseFloat((document.getElementById('pay-jumlah').value||'0').replace(/[^0-9.]/g,''))||0;
  const catatan     = (document.getElementById('pay-catatan').value||'').trim();
  const bukti       = (document.getElementById('pay-bukti').value||'').trim();

  if(!pelangganId || !tanggal) {
    showAlert('Pilih pelanggan dan tanggal bayar.','Validasi');
    return;
  }

  const btn = document.getElementById('btn-submit-pembayaran');
  const orig = btn ? btn.innerHTML : '';
  if(btn) { btn.disabled = true; btn.innerHTML = '<i class="fa-solid fa-spinner animate-spin"></i> Mengirim...'; }

  try {
    const { data: plg } = await supa.from('pelanggan').select('nama, no_layanan').eq('id', pelangganId).single();
    const { error } = await supa.from('pembayaran').insert({
      pelanggan_id:    pelangganId,
      no_layanan:      plg?.no_layanan || '',
      nama_pelanggan:  plg?.nama || '',
      tanggal_bayar:   tanggal,
      jumlah,
      catatan:         catatan || null,
      bukti_url:       bukti   || null,
      status:          'MENUNGGU',
      input_oleh:      currentUser ? currentUser.displayName : 'CS'
    });
    if(error) throw error;
    showAlert(`Pembayaran ${plg?.nama} berhasil dicatat dan menunggu konfirmasi Admin.`,'Terkirim ✅');
    tutupFormPembayaran();
    await loadDataPelanggan();
  } catch(err) {
    showAlert('Gagal simpan pembayaran: '+(err.message||''),'Error');
  }
  if(btn) { btn.disabled = false; btn.innerHTML = orig; }
}

// ── KONFIRMASI PEMBAYARAN (Admin) ─────────────────────────────
async function loadKonfirmasiPembayaran() {
  const el = document.getElementById('konfirmasi-pembayaran-list');
  if(!el) return;
  el.innerHTML = '<div class="text-xs text-slate-400 text-center py-4"><i class="fa-solid fa-spinner animate-spin mr-1"></i>Memuat...</div>';
  try {
    const { data, error } = await supa.from('pembayaran')
      .select('*')
      .eq('status','MENUNGGU')
      .order('created_at',{ascending:false});
    if(error) throw error;
    if(!data || !data.length) {
      el.innerHTML = '<div class="text-xs text-slate-400 text-center py-6"><i class="fa-solid fa-inbox text-lg block mb-1"></i>Tidak ada pembayaran yang menunggu konfirmasi.</div>';
      return;
    }
    el.innerHTML = data.map(pay => `
      <div class="p-4 bg-white dark:bg-slate-800 rounded-2xl border border-slate-200 dark:border-slate-600 space-y-3">
        <div class="flex items-start justify-between gap-2">
          <div>
            <p class="text-sm font-extrabold text-slate-900 dark:text-white">${plgText(pay.nama_pelanggan)}</p>
            <p class="text-[10px] text-slate-500"><i class="fa-solid fa-id-card mr-1"></i>No. Layanan: ${plgText(pay.no_layanan||'-')}</p>
          </div>
          <span class="px-2.5 py-1 rounded-lg text-[10px] font-black bg-amber-100 text-amber-700">Menunggu</span>
        </div>
        <div class="grid grid-cols-2 gap-2 text-xs">
          <div><span class="text-slate-400">Tgl Bayar:</span> <span class="font-semibold">${plgDate(pay.tanggal_bayar)}</span></div>
          <div><span class="text-slate-400">Jumlah:</span> <span class="font-bold text-emerald-600">${plgFmt(pay.jumlah)}</span></div>
          <div><span class="text-slate-400">Input oleh:</span> <span class="font-semibold">${plgText(pay.input_oleh)}</span></div>
          <div><span class="text-slate-400">Waktu:</span> <span class="font-semibold">${new Date(pay.created_at).toLocaleString('id-ID',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</span></div>
        </div>
        ${pay.catatan ? `<p class="text-xs text-slate-500 italic">"${plgText(pay.catatan)}"</p>` : ''}
        ${pay.bukti_url ? `<a href="${plgText(pay.bukti_url)}" target="_blank" class="text-xs text-blue-600 hover:underline flex items-center gap-1"><i class="fa-solid fa-image"></i>Lihat Bukti Pembayaran</a>` : ''}
        <div class="flex gap-2 pt-1 border-t border-slate-100 dark:border-slate-700">
          <button onclick="konfirmasiPembayaran('${pay.id}','${pay.pelanggan_id}','${pay.tanggal_bayar}',true)"
            class="flex-1 py-2 bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs rounded-lg flex items-center justify-center gap-1.5 transition-all shadow">
            <i class="fa-solid fa-check-double"></i>Sudah Bayar — Aktifkan
          </button>
          <button onclick="konfirmasiPembayaran('${pay.id}','${pay.pelanggan_id}','${pay.tanggal_bayar}',false)"
            class="flex-1 py-2 bg-rose-100 hover:bg-rose-200 text-rose-600 font-bold text-xs rounded-lg flex items-center justify-center gap-1.5 transition-all">
            <i class="fa-solid fa-xmark"></i>Tolak
          </button>
        </div>
      </div>`).join('');
  } catch(err) {
    el.innerHTML = `<div class="text-xs text-rose-500 text-center py-4">Gagal: ${plgText(err.message)}</div>`;
  }
}

async function konfirmasiPembayaran(payId, pelangganId, tanggalBayar, approve) {
  const btn = event.target.closest('button');
  const origHtml = btn ? btn.innerHTML : '';
  if(btn) { btn.disabled = true; btn.innerHTML = '<i class="fa-solid fa-spinner animate-spin"></i>'; }
  try {
    const status = approve ? 'DIKONFIRMASI' : 'DITOLAK';
    const { error: payErr } = await supa.from('pembayaran').update({
      status,
      konfirmasi_oleh: currentUser ? currentUser.displayName : 'Admin',
      konfirmasi_at:   new Date().toISOString()
    }).eq('id', payId);
    if(payErr) throw payErr;

    if(approve) {
      // Update status pelanggan → AKTIF, hitung jatuh tempo baru
      const jatuhTempo = plgAddDays(tanggalBayar, 30);
      const { error: plgErr } = await supa.from('pelanggan').update({
        status_billing:          'AKTIF',
        tanggal_bayar_terakhir:  tanggalBayar,
        tanggal_jatuh_tempo:     jatuhTempo,
        tanggal_suspend:         null,
        updated_at:              new Date().toISOString()
      }).eq('id', pelangganId);
      if(plgErr) throw plgErr;
      showAlert(`Pembayaran dikonfirmasi. Pelanggan aktif kembali.\nJatuh tempo berikutnya: ${plgDate(jatuhTempo)}`,'Berhasil ✅');
    } else {
      showAlert('Pembayaran ditolak.','Ditolak');
    }
    await loadKonfirmasiPembayaran();
  } catch(err) {
    showAlert('Gagal konfirmasi: '+(err.message||''),'Error');
  }
  if(btn) { btn.disabled = false; btn.innerHTML = origHtml; }
}

// ── JALANKAN BILLING CHECK SAAT LOAD ─────────────────────────
// Dipanggil saat app init untuk update status otomatis
window._billingCheckDone = false;
async function initBillingCheck() {
  if(window._billingCheckDone) return;
  window._billingCheckDone = true;
  await runBillingCheck();
}
